"""
Extended zip code list for saturated Greater Boston coverage.
~220 zip codes for maximum market penetration.
"""

EXTENDED_BOSTON_ZIP_CODES = [
    # ── BOSTON PROPER (Extended coverage) ──
    {'zip': '02108', 'neighborhood': 'Beacon Hill', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02109', 'neighborhood': 'North End', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02110', 'neighborhood': 'Financial District', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02111', 'neighborhood': 'Chinatown', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02113', 'neighborhood': 'North End', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02114', 'neighborhood': 'West End', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02115', 'neighborhood': 'Fenway', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02116', 'neighborhood': 'Back Bay', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02117', 'neighborhood': 'Back Bay', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02118', 'neighborhood': 'South End', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02119', 'neighborhood': 'Roxbury', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02120', 'neighborhood': 'Mission Hill', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02121', 'neighborhood': 'Dorchester', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02122', 'neighborhood': 'Dorchester', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02124', 'neighborhood': 'Dorchester', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02125', 'neighborhood': 'Dorchester', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02126', 'neighborhood': 'Mattapan', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02127', 'neighborhood': 'South Boston', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02128', 'neighborhood': 'East Boston', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02129', 'neighborhood': 'Charlestown', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02130', 'neighborhood': 'Jamaica Plain', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02131', 'neighborhood': 'Roslindale', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02132', 'neighborhood': 'West Roxbury', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02133', 'neighborhood': 'Downtown', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02134', 'neighborhood': 'Allston', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02135', 'neighborhood': 'Brighton', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02136', 'neighborhood': 'Hyde Park', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02163', 'neighborhood': 'Allston', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02199', 'neighborhood': 'Back Bay', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02203', 'neighborhood': 'Downtown', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02210', 'neighborhood': 'Seaport', 'city': 'Boston', 'state_abbr': 'MA'},
    {'zip': '02215', 'neighborhood': 'Fenway', 'city': 'Boston', 'state_abbr': 'MA'},
    
    # ── CAMBRIDGE ──
    {'zip': '02138', 'neighborhood': 'Harvard Square', 'city': 'Cambridge', 'state_abbr': 'MA'},
    {'zip': '02139', 'neighborhood': 'Central Square', 'city': 'Cambridge', 'state_abbr': 'MA'},
    {'zip': '02140', 'neighborhood': 'Porter Square', 'city': 'Cambridge', 'state_abbr': 'MA'},
    {'zip': '02141', 'neighborhood': 'East Cambridge', 'city': 'Cambridge', 'state_abbr': 'MA'},
    {'zip': '02142', 'neighborhood': 'Kendall Square', 'city': 'Cambridge', 'state_abbr': 'MA'},
    
    # ── SOMERVILLE ──
    {'zip': '02143', 'neighborhood': 'Union Square', 'city': 'Somerville', 'state_abbr': 'MA'},
    {'zip': '02144', 'neighborhood': 'Davis Square', 'city': 'Somerville', 'state_abbr': 'MA'},
    {'zip': '02145', 'neighborhood': 'Assembly Square', 'city': 'Somerville', 'state_abbr': 'MA'},
    
    # ── BROOKLINE ──
    {'zip': '02445', 'neighborhood': 'Brookline Village', 'city': 'Brookline', 'state_abbr': 'MA'},
    {'zip': '02446', 'neighborhood': 'Coolidge Corner', 'city': 'Brookline', 'state_abbr': 'MA'},
    {'zip': '02447', 'neighborhood': 'Brookline Hills', 'city': 'Brookline', 'state_abbr': 'MA'},
    
    # ── NEWTON ──
    {'zip': '02458', 'neighborhood': 'Newton', 'city': 'Newton', 'state_abbr': 'MA'},
    {'zip': '02459', 'neighborhood': 'Newton Centre', 'city': 'Newton', 'state_abbr': 'MA'},
    {'zip': '02460', 'neighborhood': 'Newtonville', 'city': 'Newton', 'state_abbr': 'MA'},
    {'zip': '02461', 'neighborhood': 'Newton Highlands', 'city': 'Newton', 'state_abbr': 'MA'},
    {'zip': '02462', 'neighborhood': 'Newton Lower Falls', 'city': 'Newton', 'state_abbr': 'MA'},
    {'zip': '02464', 'neighborhood': 'Newton Upper Falls', 'city': 'Newton', 'state_abbr': 'MA'},
    {'zip': '02465', 'neighborhood': 'West Newton', 'city': 'Newton', 'state_abbr': 'MA'},
    {'zip': '02466', 'neighborhood': 'Auburndale', 'city': 'Newton', 'state_abbr': 'MA'},
    {'zip': '02467', 'neighborhood': 'Chestnut Hill', 'city': 'Newton', 'state_abbr': 'MA'},
    {'zip': '02468', 'neighborhood': 'Waban', 'city': 'Newton', 'state_abbr': 'MA'},
    
    # ── QUINCY ──
    {'zip': '02169', 'neighborhood': 'Quincy Center', 'city': 'Quincy', 'state_abbr': 'MA'},
    {'zip': '02170', 'neighborhood': 'Wollaston', 'city': 'Quincy', 'state_abbr': 'MA'},
    {'zip': '02171', 'neighborhood': 'North Quincy', 'city': 'Quincy', 'state_abbr': 'MA'},
    {'zip': '02269', 'neighborhood': 'Quincy', 'city': 'Quincy', 'state_abbr': 'MA'},
    
    # ── INNER RING SUBURBS ──
    {'zip': '02148', 'neighborhood': 'Malden', 'city': 'Malden', 'state_abbr': 'MA'},
    {'zip': '02149', 'neighborhood': 'Everett', 'city': 'Everett', 'state_abbr': 'MA'},
    {'zip': '02150', 'neighborhood': 'Chelsea', 'city': 'Chelsea', 'state_abbr': 'MA'},
    {'zip': '02151', 'neighborhood': 'Revere', 'city': 'Revere', 'state_abbr': 'MA'},
    {'zip': '02152', 'neighborhood': 'Winthrop', 'city': 'Winthrop', 'state_abbr': 'MA'},
    {'zip': '02153', 'neighborhood': 'Medford', 'city': 'Medford', 'state_abbr': 'MA'},
    {'zip': '02155', 'neighborhood': 'Medford', 'city': 'Medford', 'state_abbr': 'MA'},
    {'zip': '02156', 'neighborhood': 'West Medford', 'city': 'Medford', 'state_abbr': 'MA'},
    {'zip': '02472', 'neighborhood': 'Watertown', 'city': 'Watertown', 'state_abbr': 'MA'},
    {'zip': '02474', 'neighborhood': 'Arlington', 'city': 'Arlington', 'state_abbr': 'MA'},
    {'zip': '02476', 'neighborhood': 'Arlington Heights', 'city': 'Arlington', 'state_abbr': 'MA'},
    {'zip': '02477', 'neighborhood': 'Belmont', 'city': 'Belmont', 'state_abbr': 'MA'},
    {'zip': '02478', 'neighborhood': 'Belmont', 'city': 'Belmont', 'state_abbr': 'MA'},
    
    # ── WALTHAM ──
    {'zip': '02451', 'neighborhood': 'Waltham', 'city': 'Waltham', 'state_abbr': 'MA'},
    {'zip': '02452', 'neighborhood': 'Waltham', 'city': 'Waltham', 'state_abbr': 'MA'},
    {'zip': '02453', 'neighborhood': 'Waltham', 'city': 'Waltham', 'state_abbr': 'MA'},
    
    # ── NORTH SHORE (Lynn, Salem, Peabody, Beverly) ──
    {'zip': '01901', 'neighborhood': 'Lynn', 'city': 'Lynn', 'state_abbr': 'MA'},
    {'zip': '01902', 'neighborhood': 'Lynn', 'city': 'Lynn', 'state_abbr': 'MA'},
    {'zip': '01903', 'neighborhood': 'Lynn', 'city': 'Lynn', 'state_abbr': 'MA'},
    {'zip': '01904', 'neighborhood': 'Lynn', 'city': 'Lynn', 'state_abbr': 'MA'},
    {'zip': '01905', 'neighborhood': 'Lynn', 'city': 'Lynn', 'state_abbr': 'MA'},
    {'zip': '01906', 'neighborhood': 'Saugus', 'city': 'Saugus', 'state_abbr': 'MA'},
    {'zip': '01907', 'neighborhood': 'Swampscott', 'city': 'Swampscott', 'state_abbr': 'MA'},
    {'zip': '01908', 'neighborhood': 'Nahant', 'city': 'Nahant', 'state_abbr': 'MA'},
    {'zip': '01915', 'neighborhood': 'Beverly', 'city': 'Beverly', 'state_abbr': 'MA'},
    {'zip': '01923', 'neighborhood': 'Danvers', 'city': 'Danvers', 'state_abbr': 'MA'},
    {'zip': '01930', 'neighborhood': 'Gloucester', 'city': 'Gloucester', 'state_abbr': 'MA'},
    {'zip': '01940', 'neighborhood': 'Lynnfield', 'city': 'Lynnfield', 'state_abbr': 'MA'},
    {'zip': '01944', 'neighborhood': 'Manchester-by-the-Sea', 'city': 'Manchester-by-the-Sea', 'state_abbr': 'MA'},
    {'zip': '01945', 'neighborhood': 'Marblehead', 'city': 'Marblehead', 'state_abbr': 'MA'},
    {'zip': '01960', 'neighborhood': 'Peabody', 'city': 'Peabody', 'state_abbr': 'MA'},
    {'zip': '01966', 'neighborhood': 'Rockport', 'city': 'Rockport', 'state_abbr': 'MA'},
    {'zip': '01970', 'neighborhood': 'Salem', 'city': 'Salem', 'state_abbr': 'MA'},
    
    # ── NORTHWEST (Lexington, Winchester, Woburn, Burlington) ──
    {'zip': '01730', 'neighborhood': 'Bedford', 'city': 'Bedford', 'state_abbr': 'MA'},
    {'zip': '01742', 'neighborhood': 'Concord', 'city': 'Concord', 'state_abbr': 'MA'},
    {'zip': '01773', 'neighborhood': 'Lincoln', 'city': 'Lincoln', 'state_abbr': 'MA'},
    {'zip': '01801', 'neighborhood': 'Woburn', 'city': 'Woburn', 'state_abbr': 'MA'},
    {'zip': '01803', 'neighborhood': 'Burlington', 'city': 'Burlington', 'state_abbr': 'MA'},
    {'zip': '01810', 'neighborhood': 'Andover', 'city': 'Andover', 'state_abbr': 'MA'},
    {'zip': '01821', 'neighborhood': 'Billerica', 'city': 'Billerica', 'state_abbr': 'MA'},
    {'zip': '01824', 'neighborhood': 'Chelmsford', 'city': 'Chelmsford', 'state_abbr': 'MA'},
    {'zip': '01826', 'neighborhood': 'Dracut', 'city': 'Dracut', 'state_abbr': 'MA'},
    {'zip': '01830', 'neighborhood': 'Haverhill', 'city': 'Haverhill', 'state_abbr': 'MA'},
    {'zip': '01832', 'neighborhood': 'Haverhill', 'city': 'Haverhill', 'state_abbr': 'MA'},
    {'zip': '01835', 'neighborhood': 'Haverhill', 'city': 'Haverhill', 'state_abbr': 'MA'},
    {'zip': '01840', 'neighborhood': 'Lawrence', 'city': 'Lawrence', 'state_abbr': 'MA'},
    {'zip': '01841', 'neighborhood': 'Lawrence', 'city': 'Lawrence', 'state_abbr': 'MA'},
    {'zip': '01842', 'neighborhood': 'Lawrence', 'city': 'Lawrence', 'state_abbr': 'MA'},
    {'zip': '01843', 'neighborhood': 'Lawrence', 'city': 'Lawrence', 'state_abbr': 'MA'},
    {'zip': '01844', 'neighborhood': 'Methuen', 'city': 'Methuen', 'state_abbr': 'MA'},
    {'zip': '01845', 'neighborhood': 'North Andover', 'city': 'North Andover', 'state_abbr': 'MA'},
    {'zip': '01850', 'neighborhood': 'Lowell', 'city': 'Lowell', 'state_abbr': 'MA'},
    {'zip': '01851', 'neighborhood': 'Lowell', 'city': 'Lowell', 'state_abbr': 'MA'},
    {'zip': '01852', 'neighborhood': 'Lowell', 'city': 'Lowell', 'state_abbr': 'MA'},
    {'zip': '01853', 'neighborhood': 'Lowell', 'city': 'Lowell', 'state_abbr': 'MA'},
    {'zip': '01854', 'neighborhood': 'Lowell', 'city': 'Lowell', 'state_abbr': 'MA'},
    {'zip': '01864', 'neighborhood': 'North Reading', 'city': 'North Reading', 'state_abbr': 'MA'},
    {'zip': '01867', 'neighborhood': 'Reading', 'city': 'Reading', 'state_abbr': 'MA'},
    {'zip': '01876', 'neighborhood': 'Tewksbury', 'city': 'Tewksbury', 'state_abbr': 'MA'},
    {'zip': '01880', 'neighborhood': 'Wakefield', 'city': 'Wakefield', 'state_abbr': 'MA'},
    {'zip': '01887', 'neighborhood': 'Wilmington', 'city': 'Wilmington', 'state_abbr': 'MA'},
    {'zip': '01890', 'neighborhood': 'Winchester', 'city': 'Winchester', 'state_abbr': 'MA'},
    {'zip': '02176', 'neighborhood': 'Melrose', 'city': 'Melrose', 'state_abbr': 'MA'},
    {'zip': '02180', 'neighborhood': 'Stoneham', 'city': 'Stoneham', 'state_abbr': 'MA'},
    {'zip': '02420', 'neighborhood': 'Lexington', 'city': 'Lexington', 'state_abbr': 'MA'},
    {'zip': '02421', 'neighborhood': 'Lexington', 'city': 'Lexington', 'state_abbr': 'MA'},
    
    # ── WEST (Weston, Wayland, Wellesley, Needham, Natick, Framingham) ──
    {'zip': '01701', 'neighborhood': 'Framingham', 'city': 'Framingham', 'state_abbr': 'MA'},
    {'zip': '01702', 'neighborhood': 'Framingham', 'city': 'Framingham', 'state_abbr': 'MA'},
    {'zip': '01760', 'neighborhood': 'Natick', 'city': 'Natick', 'state_abbr': 'MA'},
    {'zip': '01778', 'neighborhood': 'Wayland', 'city': 'Wayland', 'state_abbr': 'MA'},
    {'zip': '02030', 'neighborhood': 'Dover', 'city': 'Dover', 'state_abbr': 'MA'},
    {'zip': '02054', 'neighborhood': 'Millis', 'city': 'Millis', 'state_abbr': 'MA'},
    {'zip': '02090', 'neighborhood': 'Westwood', 'city': 'Westwood', 'state_abbr': 'MA'},
    {'zip': '02093', 'neighborhood': 'Weston', 'city': 'Weston', 'state_abbr': 'MA'},
    {'zip': '02181', 'neighborhood': 'Wellesley', 'city': 'Wellesley', 'state_abbr': 'MA'},
    {'zip': '02457', 'neighborhood': 'Babson Park', 'city': 'Wellesley', 'state_abbr': 'MA'},
    {'zip': '02481', 'neighborhood': 'Wellesley Hills', 'city': 'Wellesley', 'state_abbr': 'MA'},
    {'zip': '02482', 'neighborhood': 'Wellesley', 'city': 'Wellesley', 'state_abbr': 'MA'},
    {'zip': '02492', 'neighborhood': 'Needham', 'city': 'Needham', 'state_abbr': 'MA'},
    {'zip': '02493', 'neighborhood': 'Needham Heights', 'city': 'Needham', 'state_abbr': 'MA'},
    {'zip': '02494', 'neighborhood': 'Needham', 'city': 'Needham', 'state_abbr': 'MA'},
    
    # ── SOUTH SHORE (Braintree, Weymouth, Milton, Dedham, Norwood) ──
    {'zip': '02021', 'neighborhood': 'Canton', 'city': 'Canton', 'state_abbr': 'MA'},
    {'zip': '02025', 'neighborhood': 'Cohasset', 'city': 'Cohasset', 'state_abbr': 'MA'},
    {'zip': '02026', 'neighborhood': 'Dedham', 'city': 'Dedham', 'state_abbr': 'MA'},
    {'zip': '02027', 'neighborhood': 'Dedham', 'city': 'Dedham', 'state_abbr': 'MA'},
    {'zip': '02035', 'neighborhood': 'Foxboro', 'city': 'Foxboro', 'state_abbr': 'MA'},
    {'zip': '02038', 'neighborhood': 'Franklin', 'city': 'Franklin', 'state_abbr': 'MA'},
    {'zip': '02043', 'neighborhood': 'Hingham', 'city': 'Hingham', 'state_abbr': 'MA'},
    {'zip': '02045', 'neighborhood': 'Hull', 'city': 'Hull', 'state_abbr': 'MA'},
    {'zip': '02050', 'neighborhood': 'Marshfield', 'city': 'Marshfield', 'state_abbr': 'MA'},
    {'zip': '02052', 'neighborhood': 'Medfield', 'city': 'Medfield', 'state_abbr': 'MA'},
    {'zip': '02053', 'neighborhood': 'Medway', 'city': 'Medway', 'state_abbr': 'MA'},
    {'zip': '02061', 'neighborhood': 'Norwell', 'city': 'Norwell', 'state_abbr': 'MA'},
    {'zip': '02062', 'neighborhood': 'Norwood', 'city': 'Norwood', 'state_abbr': 'MA'},
    {'zip': '02066', 'neighborhood': 'Scituate', 'city': 'Scituate', 'state_abbr': 'MA'},
    {'zip': '02067', 'neighborhood': 'Sharon', 'city': 'Sharon', 'state_abbr': 'MA'},
    {'zip': '02072', 'neighborhood': 'Stoughton', 'city': 'Stoughton', 'state_abbr': 'MA'},
    {'zip': '02081', 'neighborhood': 'Walpole', 'city': 'Walpole', 'state_abbr': 'MA'},
    {'zip': '02184', 'neighborhood': 'Braintree', 'city': 'Braintree', 'state_abbr': 'MA'},
    {'zip': '02185', 'neighborhood': 'Braintree', 'city': 'Braintree', 'state_abbr': 'MA'},
    {'zip': '02186', 'neighborhood': 'Milton', 'city': 'Milton', 'state_abbr': 'MA'},
    {'zip': '02187', 'neighborhood': 'Milton Village', 'city': 'Milton', 'state_abbr': 'MA'},
    {'zip': '02188', 'neighborhood': 'Weymouth', 'city': 'Weymouth', 'state_abbr': 'MA'},
    {'zip': '02189', 'neighborhood': 'East Weymouth', 'city': 'Weymouth', 'state_abbr': 'MA'},
    {'zip': '02190', 'neighborhood': 'South Weymouth', 'city': 'Weymouth', 'state_abbr': 'MA'},
    {'zip': '02191', 'neighborhood': 'North Weymouth', 'city': 'Weymouth', 'state_abbr': 'MA'},
    {'zip': '02301', 'neighborhood': 'Brockton', 'city': 'Brockton', 'state_abbr': 'MA'},
    {'zip': '02302', 'neighborhood': 'Brockton', 'city': 'Brockton', 'state_abbr': 'MA'},
    {'zip': '02322', 'neighborhood': 'Avon', 'city': 'Avon', 'state_abbr': 'MA'},
    {'zip': '02324', 'neighborhood': 'Bridgewater', 'city': 'Bridgewater', 'state_abbr': 'MA'},
    {'zip': '02333', 'neighborhood': 'East Bridgewater', 'city': 'East Bridgewater', 'state_abbr': 'MA'},
    {'zip': '02338', 'neighborhood': 'Halifax', 'city': 'Halifax', 'state_abbr': 'MA'},
    {'zip': '02339', 'neighborhood': 'Hanover', 'city': 'Hanover', 'state_abbr': 'MA'},
    {'zip': '02341', 'neighborhood': 'Hanson', 'city': 'Hanson', 'state_abbr': 'MA'},
    {'zip': '02343', 'neighborhood': 'Holbrook', 'city': 'Holbrook', 'state_abbr': 'MA'},
    {'zip': '02346', 'neighborhood': 'Middleboro', 'city': 'Middleboro', 'state_abbr': 'MA'},
    {'zip': '02351', 'neighborhood': 'Abington', 'city': 'Abington', 'state_abbr': 'MA'},
    {'zip': '02359', 'neighborhood': 'Pembroke', 'city': 'Pembroke', 'state_abbr': 'MA'},
    {'zip': '02360', 'neighborhood': 'Plymouth', 'city': 'Plymouth', 'state_abbr': 'MA'},
    {'zip': '02364', 'neighborhood': 'Kingston', 'city': 'Kingston', 'state_abbr': 'MA'},
    {'zip': '02368', 'neighborhood': 'Randolph', 'city': 'Randolph', 'state_abbr': 'MA'},
    {'zip': '02370', 'neighborhood': 'Rockland', 'city': 'Rockland', 'state_abbr': 'MA'},
]
